### ISSUE TITLE
how to provide aws credentials

### ISSUE THREAD

**Issue by acamillo2** [mumoshu/aws-secret-operator#12]
I followed the instructions to install the operator in my own minikube instance. 
However the operator fail when i try to create a secret with the following log

How can i pass AWS credentials to the operator? IAM Roles?

> {"level":"error","ts":1553702614.8361397,"logger":"kubebuilder.controller","caller":"controller/controller.go:209","msg":"Reconciler error","Controller":"awssecret-controller","Request":"default/example.alessandro.hbc.com","error":"failed to compute secret for cr: failed to get json secret as map: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors","errorVerbose":"NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\nfailed to get json secret as map\ngithub.com/mumoshu/aws-secret-operator/pkg/controller/awssecret.(*ReconcileAWSSecret).newSecretForCR\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/pkg/controller/awssecret/awssecret_controller.go:154\ngithub.com/mumoshu/aws-secret-operator/pkg/controller/awssecret.(*ReconcileAWSSecret).Reconcile\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/pkg/controller/awssecret/awssecret_controller.go:107\ngithub.com/mumoshu/aws-secret-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207\ngithub.com/mumoshu/aws-secret-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:1333\nfailed to compute secret for cr\ngithub.com/mumoshu/aws-secret-operator/pkg/controller/awssecret.(*ReconcileAWSSecret).Reconcile\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/pkg/controller/awssecret/awssecret_controller.go:109\ngithub.com/mumoshu/aws-secret-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207\ngithub.com/mumoshu/aws-secret-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:1333","stacktrace":"github.com/mumoshu/aws-secret-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/mumoshu/aws-secret-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\ngithub.com/mumoshu/aws-secret-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/kuoka-yusuke/go/src/github.com/mumoshu/aws-secret-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

**Comment by emilic** [comment]
I added the following to the operator.yaml environment:

env:
  - name: AWS_REGION
    value: <your region>
  - name: AWS_ACCESS_KEY_ID
    value: <your access key>
  - name: AWS_SECRET_ACCESS_KEY
    value: <your secret>

**Comment by Zefool** [comment]
Better use IAM Roles. This way you're probably checking in secrets again.

**Comment by max-lobur** [comment]
https://github.com/uswitch/kiam
Highly recommend

**Comment by agirlnamedsophia** [comment]
Hi there! Great tool, excited to get it working! I'm trying to associate an IAM role to this deployment but I still get these errors in the secret-operator logs:

```
{"level":"error","ts":1557497207.7725396,"logger":"kubebuilder.controller","caller":"controller/controller.go:209","msg":"Reconciler error","Controller":"awssecret-controller","Request":"kube-system/example","error":"failed to compute secret for cr: failed to get json secret as map: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors","errorVerbose":"NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\nfailed to get json secret as map\ngithub.com/Betterment/aws-secret-operator/pkg/controller/awssecret.
...
```

My IAM role is attached as an annotation on the deployment spec:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-secret-operator
  namespace: kube-system
  labels:
    app: aws-secret-operator
    security_zone: ${security_zone}
    world: ${world}
    foo: "bar"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-secret-operator
  template:
    metadata:
      labels:
        name: aws-secret-operator
        app: aws-secret-operator
        security_zone: ${security_zone}
        world: ${world}
      annotations:
        iam.amazonaws.com/role: "${security_zone}_infra_secrets_operator"
```


And that role has permissions to access secrets manager. I tried to also give it the `AmazonEKSClusterPolicy` built in AWS policy but still no dice. I'm still quite new to all this kubernetes stuff, could you help me sort out what permissions are required?

**Comment by Zefool** [comment]
Pointers that might be useful: 
Roles have Principals and you can configure which entities can assume a role. There might be an error there. 
Other than that I can only imagine a spelling issue. If you compare the annotation directly with the role ARN, are they the same?

**Comment by acamillo2** [comment]
I eventually ended up writing my own operator. It runs fine in minikube and AWS.
Look at here if you like: https://github.com/acamillo/aws-secret-operator

**Comment by acamillo2** [comment]
I eventually ended up writing my own operator. It runs fine in minikube and AWS.
Look at here if you like: https://github.com/acamillo/aws-secret-operator

**Comment by ecout** [comment]
> https://github.com/uswitch/kiam
> Highly recommend

If you're in EKS 1.1.3 you can use Service Accounts with AWS roles and avoid the complications of those third party controllers.

**Comment by ecout** [comment]
> Hi there! Great tool, excited to get it working! I'm trying to associate an IAM role to this deployment but I still get these errors in the secret-operator logs:
> 
> ```
> {"level":"error","ts":1557497207.7725396,"logger":"kubebuilder.controller","caller":"controller/controller.go:209","msg":"Reconciler error","Controller":"awssecret-controller","Request":"kube-system/example","error":"failed to compute secret for cr: failed to get json secret as map: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors","errorVerbose":"NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\nfailed to get json secret as map\ngithub.com/Betterment/aws-secret-operator/pkg/controller/awssecret.
> ...
> ```
> 
> My IAM role is attached as an annotation on the deployment spec:
> 
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: aws-secret-operator
>   namespace: kube-system
>   labels:
>     app: aws-secret-operator
>     security_zone: ${security_zone}
>     world: ${world}
>     foo: "bar"
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       name: aws-secret-operator
>   template:
>     metadata:
>       labels:
>         name: aws-secret-operator
>         app: aws-secret-operator
>         security_zone: ${security_zone}
>         world: ${world}
>       annotations:
>         iam.amazonaws.com/role: "${security_zone}_infra_secrets_operator"
> ```
> 
> And that role has permissions to access secrets manager. I tried to also give it the `AmazonEKSClusterPolicy` built in AWS policy but still no dice. I'm still quite new to all this kubernetes stuff, could you help me sort out what permissions are required?

How do you assign the role to the cluster on the AWS side?
Please look into the AWS STS flow. Roles are nothing but auto-rotated IAM keys. If your code/instance/service doesn't have a way to make a request to the STS service for those keys anything else you do is futile.
