### ISSUE TITLE
Use parameter store now that higher throughput is available?

### ISSUE THREAD

**Issue by kenske** [mumoshu/aws-secret-operator#14]
AWS recently added the capability to increase throughput for SSM parameter store:

https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-throughput.html

Is there a chance `aws-secret-operator` could be updated to support it?

**Comment by mumoshu** [comment]
Definitely adding SSM-based backend to this operator makes sense. Acrtually that's why this operator doesn't contain the word secrets-manager in it.
