### ISSUE TITLE
AWS ACM feature support request 

### ISSUE THREAD

**Issue by marcellodesales** [mumoshu/aws-secret-operator#26]
Hey there,

Is there any possibility to integrate this AWS ACM to retrieve ACM as secrets? I'm asking because a CERTs can be stored as secrets...

*  Is there such a possibility? 
* Could you provide the path to implement such feature if that's possible?
* Would you suggest to extend or fork your solution?

thank you
Marcello

**Comment by ecout** [comment]
What kind of certs are you trying to retrieve, you cannot retrieve cert and keys from public certs only from private ones after you've uploaded your own CA cert. So how do you plan to use them without their private key?

**Comment by marcellodesales** [comment]
@ecout I guess then we can't proceed with this since we would need the private key.
