### ISSUE TITLE
New tagged build?

### ISSUE THREAD

**Issue by Geethree** [mumoshu/aws-secret-operator#44]
Hey @mumoshu! 

First off, thank you for a wonderful project!

Following #43 it would be great if you could trigger a tagged artifact in dockerhub? It appears that the latest image was built after, but, using latest can get tricky in deployments. 

Thoughts? Happy to help however I can.

**Comment by mumoshu** [comment]
@Geethree Hey! Just tagged v0.4.0. The image will be available via DockerHub soon. Thanks for reminding me 👍
