### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by h7kanna** [mumoshu/aws-secret-operator#5]
Hi, 
Can you add license for this project?

Nice effort!!
Thanks,

**Comment by myniva** [comment]
On a legal level, "No License" means "nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation". See https://choosealicense.com/no-permission/

The absence of a clear license statement will prevent many interested parties of using and contributing to this useful piece of software.

**Comment by ecout** [comment]
@myniva  Why doesn't github enforce that for public repos?

**Comment by endophage** [comment]
@mumoshu you can close this issue now 😃

**Comment by mumoshu** [comment]
@endophage Thanks for your help and the reminder ☺️
Everyone, we now use Apache 2.0 license as proposed by @endophage
