### ISSUE TITLE
Insufficient RBAC permissions related to leader election in operator-lib/leader

### ISSUE THREAD

**Issue by tatusl** [mumoshu/aws-secret-operator#58]
### Issue description

When running cluster-scoped aws-secret-operator with [Kubernetes manifests provided by the project](https://github.com/mumoshu/aws-secret-operator/tree/main/deploy/cluster_scoped), the following error is logged occassionally:

```
2022-06-16T13:44:37Z    ERROR   leader  Failed to get Node      {"Node.Name": "$NODE_NAME_REDACED", "error": "nodes \"$NODE_NAME_REDACTED\" is forbidden: User \"system:serviceaccount:kube-system:aws-secret-operator\" cannot get resource \"nodes\" in API group \"\" at the cluster scope"}
github.com/operator-framework/operator-lib/leader.getNode
        /go/pkg/mod/github.com/operator-framework/operator-lib@v0.10.0/leader/leader.go:269
github.com/operator-framework/operator-lib/leader.isNotReadyNode
        /go/pkg/mod/github.com/operator-framework/operator-lib@v0.10.0/leader/leader.go:277
github.com/operator-framework/operator-lib/leader.Become
        /go/pkg/mod/github.com/operator-framework/operator-lib@v0.10.0/leader/leader.go:182
github.com/mumoshu/aws-secret-operator/cmd.run
        /workspace/cmd/root.go:122
github.com/mumoshu/aws-secret-operator/cmd.glob..func1
        /workspace/cmd/root.go:60
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main
        /workspace/main.go:10
runtime.main
        /usr/local/go/src/runtime/proc.go:255
```

It seems that this is caused by leader-election mechanism in [operator-lib/leader](https://github.com/operator-framework/operator-lib/blob/main/leader/leader.go) library.

[RBAC](https://github.com/mumoshu/aws-secret-operator/blob/main/deploy/cluster_scoped/rbac.yaml) provided in this project doesn't include `get` for `nodes`.

**So my question is that should this permission be included in the RBAC provided by the project**

### Steps to reproduce

Run aws-secret-operator in cluster-scoped mode.

### Expected behaviour

aws-secret-operator runs without errors.

### Environment

 **aws-secret-operator-version:** v0.5.2

**EKS Kubernetes version:** 1.21

### Additional context and suggested fix

I'm happy to create PR adding the missing "get nodes" permissions to RBAC provided by the project, if we agree that it's reasonable action.

**Comment by mumoshu** [comment]
@tatusl Good catch! I totally missed it. I'd appreciate it if you could submit the PR. Thanks ☺️
